name: Go
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
      with:
        path: 'src/'

    - name: Get dependencies
      run: |
        echo $GITHUB_WORKSPACE
        go get -v -t -d ./...
        if [ -f Gopkg.toml ]; then
            go get -u github.com/golang/dep/cmd/dep
            export PATH="$PATH:/home/runner/go/bin"
            dep ensure
        fi
    - name: Test
      run: go test -v .
      
    - name: Build
      run: go build -v .
