name: Go Build
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.13
      uses: actions/setup-go@v2-beta
      with:
        go-version: '^1.13.1'
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Get dependencies
      run: |
        set -eux
        curl -L -s https://github.com/golang/dep/releases/download/v0.5.0/dep-linux-amd64 -o "$GOPATH/bin/dep"
        chmod +x "${GOPATH}/bin/dep"
        dep ensure -vendor-only

    - name: Build
      run: go build -v .
