name: Go Build
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Install Go
      run: |
        wget https://dl.google.com/go/go1.13.7.linux-amd64.tar.gz
        sudo tar -xvf go1.13.7.linux-amd64.tar.gz
        sudo mv go /usr/local
        export GOROOT=/usr/local/go
        export GOPATH=$HOME/go
        export PATH=$GOPATH/bin:$GOROOT/bin:$PATH
        go version

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Get dependencies
      run: |
        set -eux
        curl -L -s https://github.com/golang/dep/releases/download/v0.5.0/dep-linux-amd64 -o "$GOPATH/bin/dep"
        chmod +x "${GOPATH}/bin/dep"
        dep ensure -vendor-only

    - name: Build
      run: go build -v .
