name: Go Test
on: [push]
jobs:
  mp-logistic:
    name: MP-Logistic
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - name: run
      uses: cedrickring/golang-action@1.4.1
      with:
        args: ls -la /github/home
      env:
        PROJECT_PATH: ./
